# 官方文档：https://doc.egernapp.com
#
# Author:https://github.com/Repcz
# TG:https://t.me/QVQ_Channel
# 以 ';' 或 '#' 或 '//' 开头的配置文件行为注释行
#
# Egern Version ≥ 1.22.0
#
# 最后更新时间: 2024-09-03 21:45
#
# ================

# TUN模式
vif_only: true

# 劫持 DNS 服务器
hijack_dns:
- '*:53'

# 自定义MaxMind数据库
geoip_db_url: https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country.mmdb

# 代理延迟测试
proxy_latency_test_url: http://connectivitycheck.gstatic.com/generate_204
# 直连延迟测试
direct_latency_test_url: http://connectivitycheck.platform.hicloud.com/generate_204

dns:
  # DNS 引导器：用于解析上游DNS(DoT、DoH、DoQ)，默认 system
  bootstrap:
    - system
    - 180.184.1.1
    - 223.5.5.5
    - 119.29.29.29

  # 上游 DNS 服务器
  upstreams:
    # 国内公共加密 DNS
    Domestic-Encrypted-DNS:
    - quic://dns.alidns.com
    - https://doh.pub/dns-query

  # DNS 转发规则
  forward:
  # BiliBili
  - wildcard: # BiliBili upos视频服务器（阿里云）
      match: 'upos-sz-mirrorali.bilivideo.com'
      value: quic://dns.alidns.com
  - wildcard: # BiliBili upos视频服务器（阿里云）
      match: 'upos-sz-mirrorali?.bilivideo.com'
      value: quic://dns.alidns.com
  - wildcard: # BiliBili upos视频服务器（阿里云）
      match: 'upos-sz-mirrorali??.bilivideo.com'
      value: quic://dns.alidns.com
  - wildcard: # BiliBili upos视频服务器（百度云）
      match: 'upos-sz-mirrorbos.bilivideo.com'
      value: 180.76.76.76
  - wildcard: # BiliBili upos视频服务器（腾讯云）
      match: 'upos-sz-mirrorcos.bilivideo.com'
      value: https://doh.pub/dns-query
  - wildcard: # BiliBili upos视频服务器（腾讯云）
      match: 'upos-sz-mirrorcos?.bilivideo.com'
      value: https://doh.pub/dns-query
  - wildcard: # BiliBili upos视频服务器（腾讯云）
      match: 'upos-sz-mirrorcos??.bilivideo.com'
      value: https://doh.pub/dns-query
  - wildcard: # BiliBili upos视频服务器（百度云）
      match: 'upos-sz-upcdnbd??.bilivideo.com'
      value: 180.76.76.76
  - wildcard: # BiliBili upos视频服务器（腾讯云）
      match: 'upos-sz-upcdntx.bilivideo.com'
      value: https://doh.pub/dns-query

  - proxy_rule_set: # 国内域名规则集
      match: https://raw.githubusercontent.com/Repcz/Tool/X/Egern/Rules/ChinaDomain.yaml
      value: system # 使用系统 DNS 解析
      update_interval: 86400
  - wildcard: # 通配符规则
      match: '*'
      value: Domestic-Encrypted-DNS

  hosts: # 域名映射

    # > IPv6
    ip6-localhost: ::1 # IPv6 Localhost
    ip6-loopback: ::1 # IPv6 Loopback
    ip6-localnet: fe00::0 # IPv6 Link-Local
    ip6-mcastprefix: ff00::0 # IPv6 Multicast
    ip6-allnodes: ff02::1 # IPv6 All Nodes
    ip6-allrouters: ff02::2 # IPv6 All Routers
    ip6-allhosts: ff02::3 # IPv6 All Hosts

    # > Encrypted DNS
    dns.google: 8.8.8.8, 8.8.4.4, 2001:4860:4860::8888, 2001:4860:4860::8844 # https://dns.google/dns-query
    dns64.dns.google: 2001:4860:4860::6464, 2001:4860:4860::64 # https://dns64.dns.google/dns-query
    cloudflare-dns.com: 104.16.249.249, 104.16.248.249, 2606:4700::6810:f8f9, 2606:4700::6810:f9f9 #https://cloudflare-dns.com/dns-query
    1dot1dot1dot1.cloudflare-dns.com: 1.1.1.1, 1.0.0.1, 2606:4700:4700::1001, 2606:4700:4700::1111 # 1dot1dot1dot1.cloudflare-dns.com:853
    one.one.one.one: 1.1.1.1, 1.0.0.1, 2606:4700:4700::1001, 2606:4700:4700::1111 # one.one.one.one:853
    dns.alidns.com: 223.5.5.5, 223.6.6.6, 2400:3200:baba::1, 2400:3200::1 # https://dns.alidns.com/dns-query
    doh.pub: 1.12.12.12, 120.53.53.53 # https://doh.pub/dns-query
    dot.pub: 1.12.12.12, 120.53.53.53 # dot.pub:853
    doh.360.cn: 23.6.48.18, 112.65.69.15 # https://doh.360.cn/dns-query
    dot.360.cn: 101.198.198.198, 101.198.199.200, 101.198.192.33, 112.65.69.15 # dot.360.cn:853
    dns.twnic.tw: 101.101.101.101, 2001:de4::101, 2001:de4::102 # https://dns.twnic.tw/dns-query
    ordns.he.net: 74.82.42.42, 2001:470:20::2 # https://ordns.he.net/dns-query

    # > Modify Contents
    # services.googleapis.cn: 74.125.193.94 # Google API Services China
    talk.google.com: 108.177.125.188 # Firebase Cloud Messaging
    mtalk.google.com: 108.177.125.188, 2404:6800:4008:c07::bc, 142.250.31.188 # Firebase Cloud Messaging
    alt1-mtalk.google.com: 3.3.3.3, 2607:f8b0:4023:c0b::bc, 64.233.171.188 # Firebase Cloud Messaging
    alt2-mtalk.google.com: 3.3.3.3, 142.250.115.188 # Firebase Cloud Messaging
    alt3-mtalk.google.com: 74.125.200.188, 173.194.77.188 # Firebase Cloud Messaging
    alt4-mtalk.google.com: 74.125.200.188, 173.194.219.188 # Firebase Cloud Messaging
    alt5-mtalk.google.com: 3.3.3.3, 2607:f8b0:4023:1::bc, 142.250.112.188 # Firebase Cloud Messaging
    alt6-mtalk.google.com: 3.3.3.3, 172.217.197.188 # Firebase Cloud Messaging
    alt7-mtalk.google.com: 74.125.200.188, 2607:f8b0:4002:c03::bc, 108.177.12.188 # Firebase Cloud Messaging
    alt8-mtalk.google.com: 3.3.3.3 # Firebase Cloud Messaging
    # dl.google.com: 180.163.151.161 # Google CDN
    # dl.l.google.com: 180.163.151.161 # Google CDN

    # > Modify Contents
    blog.google: server:119.29.29.29 # Google Blog
    googletraveladservices.com: server:119.29.29.29 # Google Flights
    dl.google.com: server:119.29.29.29 # Google Download
    dl.l.google.com: server:119.29.29.29 # Google Download
    clientservices.googleapis.com: server:119.29.29.29 # Google Chrome
    update.googleapis.com: server:119.29.29.29 # Google Update
    translate.googleapis.com: server:119.29.29.29 # Google Translate
    fonts.googleapis.com: server:119.29.29.29 # Google Fonts
    fonts.gstatic.com: server:119.29.29.29 # Google Fonts
    stun.l.google.com: system # Google STUN
    stun?.l.google.com: system # Google STUN

    # > Router Admin Panel
    '*.id.ui.direct': system # Ubiquiti Unifi Network App
    # unifi.ui.com: system # Ubiquiti Unifi Portal
    unifi.local: system # Ubiquiti Unifi OS
    # network.unifi.ui.com: system # Ubiquiti Unifi Controller
    amplifi.lan: system # Ubiquiti Amplifi Router
    router.synology.com: system # Synology Router
    sila.razer.com: system # Razer Sila Router
    router.asus.com: system # Asus Router
    routerlogin.net: system # Netgear Router
    orbilogin.com: system # Netgear Obri Router
    www.LinksysSmartWiFi.com: system # Linksys Router
    LinksysSmartWiFi.com: system # Linksys Router
    myrouter.local: system # Linksys Router
    instant.arubanetworks.com: system # Aurba Router
    setmeup.arubanetworks.com: system # Aurba Router
    www.miwifi.com: system # 小米 Mi WiFi Router
    miwifi.com: system # 小米 Mi WiFi Router
    mediarouter.home: system # 华为 Huawei Router
    tplogin.cn: system # TP-Link Router
    tplinklogin.net: system # TP-Link Router
    tplinkwifi.net: system # TP-Link Router
    melogin.cn: system # 水星 MERCURY Router
    falogin.cn: system # 迅捷 FAST Router
    tendawifi.com: system # 腾达 Tenda Router
    leike.cc: system # 磊科 Netcore Router
    zte.home: system # 中兴 ZTE Router
    p.to: system # 斐讯 PHICOMM Router
    phicomm.me: system # 斐讯 PHICOMM Router
    hiwifi.com: system # 极路由 HiWiFi Router
    peiluyou.com: system # 迅雷路由
    _hotspot_.m2m: system # M2M routers at MiFi Hotspot
    hotspot.cslwifi.com: system # csl Wi-Fi

  # 公网 IP 地址查询
  public_ip_lookup_url: https://ifconfig.me/ip

policy_groups:
- external:
    name: 手动选择
    type: select
    urls:
    - http://your-service-provider
    hidden: false
    icon: https://raw.githubusercontent.com/Repcz/Tool/X/Egern/Photo/ICON/Egern.png
- select:
    name: 国外网站
    policies:
    - 香港节点
    - 美国节点
    - 狮城节点
    - 日本节点
    - 台湾节点
    - 手动选择
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Global.png
- select:
    name: 国际媒体
    policies:
    - 香港节点
    - 美国节点
    - 狮城节点
    - 日本节点
    - 台湾节点
    - 手动选择
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/YouTube.png
- select:
    name: 微软服务
    policies:
    - 香港节点
    - 美国节点
    - 狮城节点
    - 日本节点
    - 台湾节点
    - 手动选择
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Microsoft.png
- select:
    name: 谷歌服务
    policies:
    - 香港节点
    - 美国节点
    - 狮城节点
    - 日本节点
    - 台湾节点
    - 手动选择
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Google_Search.png
- select:
    name: 电报消息
    policies:
    - 香港节点
    - 美国节点
    - 狮城节点
    - 日本节点
    - 台湾节点
    - 手动选择
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Telegram.png
- select:
    name: 推特消息
    policies:
    - 香港节点
    - 美国节点
    - 狮城节点
    - 日本节点
    - 台湾节点
    - 手动选择
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Twitter.png
- select:
    name: AI
    policies:
    - 香港节点
    - 美国节点
    - 狮城节点
    - 日本节点
    - 台湾节点
    - 手动选择
    icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/OpenAI.png
- select:
    name: 游戏平台
    policies:
    - 香港节点
    - 美国节点
    - 狮城节点
    - 日本节点
    - 台湾节点
    - 手动选择
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Game.png
- select:
    name: Emby
    policies:
    - 手动选择
    flatten: true
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Emby.png
- select:
    name: 兜底分流
    policies:
    - 香港节点
    - 美国节点
    - 狮城节点
    - 日本节点
    - 台湾节点
    - 手动选择
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Final.png
- auto_test:
    name: 香港节点
    policies:
    - 手动选择
    flatten: true
    filter: (?i)🇭🇰|香港|(\b(HK|Hong)\b)
    tolerance: 0
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Hong_Kong.png
- auto_test:
    name: 美国节点
    policies:
    - 手动选择
    flatten: true
    filter: (?i)🇺🇸|美国|洛杉矶|圣何塞|(\b(US|United States)\b)
    tolerance: 0
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/United_States.png
- auto_test:
    name: 狮城节点
    policies:
    - 手动选择
    flatten: true
    filter: (?i)🇸🇬|新加坡|狮|(\b(SG|Singapore)\b)
    tolerance: 0
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Singapore.png
- auto_test:
    name: 日本节点
    policies:
    - 手动选择
    flatten: true
    filter: (?i)🇯🇵|日本|东京|(\b(JP|Japan)\b)
    tolerance: 0
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Japan.png
- auto_test:
    name: 台湾节点
    policies:
    - 手动选择
    flatten: true
    filter: (?i)🇨🇳|🇹🇼|台湾|(\b(TW|Tai|Taiwan)\b)
    tolerance: 0
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/China.png

rules:
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/Direct.yaml
    policy: DIRECT
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/Reject.yaml
    policy: REJECT
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/AI.yaml
    policy: OpenAI
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/Github.yaml
    policy: 微软服务
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/OneDrive.yaml
    policy: 微软服务
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/Microsoft.yaml
    policy: 微软服务
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/YouTube.yaml
    policy: 谷歌服务
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/Google.yaml
    policy: 谷歌服务
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/Telegram.yaml
    policy: 电报消息
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/Twitter.yaml
    policy: 推特消息
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/Game.yaml
    policy: 游戏平台
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/Emby.yaml
    policy: Emby
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/Bahamut.yaml
    policy: 国际媒体
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/Disney.yaml
    policy: 国际媒体
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/HBO.yaml
    policy: 国际媒体
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/Netflix.yaml
    policy: 国际媒体
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/Spotify.yaml
    policy: 国际媒体
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/PrimeVideo.yaml
    policy: 国际媒体
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/TikTok.yaml
    policy: 国际媒体
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/ProxyGFW.yaml
    policy: 国外网站
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/AppleProxy.yaml
    policy: 国外网站
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/Apple.yaml
    policy: DIRECT
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/Lan.yaml
    policy: DIRECT
- geoip:
    match: CN
    policy: DIRECT
- default:
    policy: 兜底分流
mitm:
  enabled: true